### ISSUE TITLE
Missing config_file and source data

### ISSUE THREAD

**Issue by zhuliwen** [only-changer/GeneraLight#2]
It seems that the `config_file` is missing when I try to run `run_cluster_maml.py`, can you provide me with a config file or source data for successfully running?

**Comment by zhuliwen** [comment]
I found the config file provided at [cityflow.readthedocs.io](https://cityflow.readthedocs.io/en/latest/start.html?highlight=config#other-api ).

**Comment by TomorrowIsAnOtherDay** [comment]
Hello. Have you run the code successfully. I have the same problem running the code.

**Comment by zhuliwen** [comment]
> Hello. Have you run the code successfully. I have the same problem running the code.

Yes, it works, please refer to the config example in the tutorial and make the appropriate path changes.

**Comment by TomorrowIsAnOtherDay** [comment]
Thanks for your reply. Hope it works.

**Comment by Sobbbbbber** [comment]
> > Hello. Have you run the code successfully. I have the same problem running the code.
> 
> Yes, it works, please refer to the config example in the tutorial and make the appropriate path changes.

Hello, guys. Have you encountered the error when running the code? And which dataset do you use to conduct experiments?

`actions.append(agent.get_action([meta_env[n].world.intersections[agent_id].current_phase],
                                                 meta_last_obs[n][agent_id]))`
in run_cluster_maml.py Line 158.

ValueError: could not broadcast input array from shape (8) into shape (1)

@zhuliwen
